
server:
  port: 7400

spring:
  application:
    name: changgou-search-service
  data:
    elasticsearch:
      client:
        reactive:
          socket-timeout: 60000
          connection-timeout: 60000



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://47.98.236.132:7001/eureka

  instance:
    instance-id: search-service-7400
    prefer-ip-address: true

ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 60000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 10000

feign:
  hystrix:
    # 开启服务熔断
    enabled: true