server:
  port: 7001

spring:
  application:
    name: eureka-register-center
eureka:
  instance:
    # eureka服务端的名称
    hostname: localhost
  client:
    # false表示不向服务注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，职责就是维护服务端实例，不需要去检索服务
    fetch-registry: false
    # 设置与Eureaka Server交互的地址查询服务和注册服务都需要用这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/