server:
  port: 7010

spring:
  application:
    name: changgou-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-service
          uri: lb://changgou-goods-service
          predicates:
            - Path=/tbBrand/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowOrigins: "*"
            allowMethods:
              - GET
              - POST
              - DELETE
              - PUT

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://47.98.236.132:7001/eureka

  instance:
    instance-id: gateway-service-7010
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug