server:
  port: 7800

spring:
  application:
    name: changgou-canal-service

canal:
  client:
    instances:
      #example为canal的instance名称
      example:
        host: 192.168.186.100
        port: 11111

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: canal-service-7800
    prefer-ip-address: true
