server:
  port: 7800

spring:
  application:
    name: changgou-canal-service
  #rabbitmq:
  #  host: 192.168.186.100

canal:
  client:
    instances:
      #example为canal的instance名称
      example:
        host: 192.168.186.100
        port: 11111


