server:
  port: 8081

spring:
  application:
    name: changgou-goods-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/changgou?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tiger
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 5000
      # 状态监控
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # 监控过滤器
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      # druid 监控页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: root

  cache:
    type: ehcache


mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    # dao 开启 debug 模式 mybatis 输入 sql
    com.dhcc.dao: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://47.98.236.132:7001/eureka

  instance:
    instance-id: goods-service-8081
    prefer-ip-address: true
